version: "3"

services:

  # Proxies requests to internal service
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverese_proxy_demo
    depends_on:
      - service_a
      - service_b
      - service_c
    volumes:
      - ./api_gateway(reverse_proxy)/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - 80:80
    
  service_a:
    image: service_a
    container_name: service_a
    build:
      context: ./service_a
    ports:
      - 5000:5000
    restart: on-failure
  
  service_b:
    image: service_b
    container_name: service_b
    build:
      context: ./service_b
    ports:
      - 5001:5001
    restart: on-failure
  
  service_c:
    image: service_c
    container_name: service_c
    build:
      context: ./service_c
    ports:
      - 5002:5002
    restart: on-failure